/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AACJni */

#ifndef _Included_AACJni
#define _Included_AACJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AACJni
 * Method:    InitAACDecoder
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_AACJni_InitAACDecoder
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     AACJni
 * Method:    AACDecoderGetStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AACJni_AACDecoderGetStatus
  (JNIEnv *, jobject);

/*
 * Class:     AACJni
 * Method:    AACDecodeFrame
 * Signature: ([B[II)I
 */
JNIEXPORT jint JNICALL Java_AACJni_AACDecodeFrame
  (JNIEnv *, jobject, jbyteArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
