/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sample1 */

#ifndef _Included_Sample1
#define _Included_Sample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sample1
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Sample1_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     Sample1
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Sample1_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Sample1
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Sample1_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Sample1
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Sample1_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Sample1
 * Method:    InitAACDecoder
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Sample1_InitAACDecoder
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Sample1
 * Method:    AACDecoderGetStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Sample1_AACDecoderGetStatus
  (JNIEnv *, jobject);

/*
 * Class:     Sample1
 * Method:    AACDecodeFrame
 * Signature: ([B[II)I
 */
JNIEXPORT jint JNICALL Java_Sample1_AACDecodeFrame
  (JNIEnv *, jobject, jbyteArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
