/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld_EnumTest */

#ifndef _Included_HelloWorld_EnumTest
#define _Included_HelloWorld_EnumTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
